name: JS Validation

on:
  push:
    branches: ["*"]
    paths-ignore:
      - "README.md"

jobs:
  js-validator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Validate JS
        run: |
          echo "Validating JS..."
          JS_FILES=$(find . -name "*.js")
          if [ -z "$JS_FILES" ]; then
            echo "No JS files found, skipping validation."
            exit 0
          fi
          for file in $JS_FILES; do
            echo "Checking $file"
            node --check "$file"
          done

